[[constraint]]
  name = "github.com/go-chi/chi"
  version = "^3.3.2"

[[constraint]]
  name = "github.com/go-chi/render"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "^0.0.2"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "^1.0.2"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "^1.3.0"

[[constraint]]
  name = "github.com/gojektech/heimdall"
  version = "3.0.0"

[[constraint]]
  name = "github.com/hashicorp/errwrap"
  branch = "master"
  
[[constraint]]
  name = "github.com/felixge/httpsnoop"
  version = "1.0.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.8.0"

[[constraint]]
  name = "github.com/uber-go/tally"
  version = "3.3.6"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.11.2"
